name: Build and Release LaTeX Document

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Compile LaTeX document with XeTeX
        run: |
          xelatex card.tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: card-pdf
          path: card.pdf

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: card.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
